export type TelegramEventCardInput = {
  eventId: string;
  title: string;
  activity: string;
  date: string;
  time: string;
  address: string;
  participants: number;
  capacity: number;
  icon: string;
  inviteUrl: string;
  mapUrl?: string;
  city: string;
  durationMinutes?: number;
  price: number;
  level: string;
  format: string;
  environment: string;
  isSport?: boolean;
  weather?: {
    icon: string;
    temperature: number;
